[program:rivescript]
directory=/www/wwwroot/rivescript-app
command=/www/wwwroot/rivescript-app/.venv/bin/uvicorn main:app --host 127.0.0.1 --port 8017 --proxy-headers
autostart=true
autorestart=true
startsecs=5
stopwaitsecs=10
user=root
stdout_logfile=/www/wwwroot/rivescript-app/logs/uvicorn.stdout.log
stderr_logfile=/www/wwwroot/rivescript-app/logs/uvicorn.stderr.log
environment=PYTHONUNBUFFERED="1"
